export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS ';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL ='ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const LOGOUT = 'LOGOUT';

/* SPINNER */
export const SPINNER_ACTIVATED = 'SPINNER_ACTIVATED';
export const SPINNER_DISABLED = 'SPINNER_DISABLED';

/*  UPLOAD DOCUMENT*/
export const DOCUMENT_SUCCESS= 'DOCUMENT_SUCCESS';
export const DOCUMENT_FAIL = 'DOCUMENT_FAIL';

/* ALERT FAIL */
export const ALERT_FAIL_ACTIVATED = 'ALERT_FAIL_ACTIVATED';
export const ALERT_FAIL_DISABLED = 'ALERT_FAIL_DISABLED';

/* ALERT SUCCESS */
export const ALERT_SUCCESS_ACTIVATED ='ALERT_SUCCESS_ACTIVATED';
export const ALERT_SUCCESS_DISABLED = 'ALERT_SUCCESS_DISABLED';


/* RESTORE PROCESS ALERT IF A ENDPOINT FAIL*/
export const RESTORE_PROCESS ='RESTORE PROCESS';
/* SAVE DOCUMENT  */
export const DOCUMENT_SAVE_SUCCESS ='DOCUMENT_SAVE_SUCCESS';
export const DOCUMENT_SAVE_FAILED = 'DOCUMENT_SAVE_FAILED';

/* SHOW DOCUMENT */
export const CANDIDATES_GET_SUCCESS ='CANDIDATES_GET_SUCCESS';
export const CANDIDATES_GET_FAILED = 'CANDIDATES_GET_FAILED';

/*  RESTORE PROCESS ALERT IF A ENDPOINT FAIL */


/* SKIllS */
export const SKILLS_GET_SUCCESS = 'SKILLS_GET_SUCCESS';
export const SKILLS_GET_FAIL= 'SKILLS_GET_FAIL';
export const SKILLS_POST_SUCCESS = 'SKILLS_POST_SUCCESS';
export const SKILLS_POST_FAIL= 'SKILLS_POST_FAIL';
/* SUBJECT */

export const SUBJECT_POST_SUCCESS = 'SUBJECT_POST_SUCCESS';
export const SUBJECT_POST_FAIL= 'SUBJECT_POST_FAIL';
/* PRACTICE */
export const PRACTICES_SUBJECTS_GET_SUCCESS = 'PRACTICES_SUBJECTS_GET_SUCCESS';
export const PRACTICES_SUBJECTS_GET_FAIL= 'PRACTICES_SUBJECTS_GET_FAIL';

export const PRACTICE_POST_SUCCESS = 'PRACTICE_POST_SUCCESS';
export const PRACTICE_POST_FAIL= 'PRACTICE_POST_FAIL';

export const PRACTICE_DELETE_SUCCESS = 'PRACTICE_DELETE_SUCCESS';
export const PRACTICE_DELETE_FAIL= 'PRACTICE_DELETE_FAIL';

/* RESTORE STATUS 200 */

export const RESTORE_STATUS_200 =  "RESTORE_STATUS_200"